name: Run unit tests for ML workflows

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Check Python
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install package
        run: python -m pip install -r requirements.txt
      - name: Run unit tests and generate coverage report
        run: python -m pytest --cov-report term --cov-report xml:coverage.xml --cov=src tests/
      - name: Upload coverage report to GitHub artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-xml
          path: coverage.xml