name: Run unit tests for ML workflows

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    name: Check Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Only needed if using setuptools-scm
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package
        run: python -m pip install -r requirements.txt
      - name: Run unit tests and generate coverage report
        run: python -m pytest --cov-report term --cov-report xml:coverage.xml --cov=src tests/
